Repository wanted-pre-onboarding-backend-team-7/BABA, pull requests merged in 2024-08, with the labels that each got.

#2 [SETTING] 프로젝트 패키지 분리
  src/main/java/org/example/baba/common/dummy.txt
  src/main/java/org/example/baba/controller/dto/request/dummy.txt
  src/main/java/org/example/baba/controller/dto/response/dummy.txt
  src/main/java/org/example/baba/domain/enums/dummy.txt
  src/main/java/org/example/baba/repository/dummy.txt
  src/main/java/org/example/baba/service/dummy.txt
  src/main/resources/application.yml
Labels: euna, SETTING

#12 [FEAT] Custom Exception 및 Exception Handler 구현
  build.gradle
  script/pre-commit
  src/main/java/org/example/baba/BabaApplication.java
  src/main/java/org/example/baba/exception/CustomException.java
  src/main/java/org/example/baba/exception/CustomExceptionHandler.java
  src/main/java/org/example/baba/exception/exceptionType/CommonExceptionType.java
  src/main/java/org/example/baba/exception/exceptionType/ExceptionType.java
  src/test/java/org/example/baba/BabaApplicationTests.java
Labels: FEAT, euna

#7 [FEAT] Post 엔티티 정의
  src/main/java/org/example/baba/domain/Post.java
  src/main/java/org/example/baba/domain/enums/SNSType.java
  src/main/java/org/example/baba/domain/enums/dummy.txt
Labels: FEAT

#17 #[CHORE] build-gradle 호환성 수정 확인
  build.gradle
Labels: Chore

#22 [CHORE] build.gradle 의존성 추가
  build.gradle
Labels: Chore

#23 [FEAT] 비밀번호 검증 어노테이션 생성
  src/main/java/org/example/baba/common/anotation/PasswordValidator.java
  src/main/java/org/example/baba/common/anotation/ValidPassword.java
Labels: ✨ Feature

#26 [FEAT] PostHashTagMap Entity 정의
  src/main/java/org/example/baba/domain/PostHashTagMap.java
Labels: ✨ Feature

#28 [FEAT] MemberRepository 생성
  src/main/java/org/example/baba/common/dummy.txt
  src/main/java/org/example/baba/repository/MemberRepository.java
  src/main/java/org/example/baba/repository/dummy.txt
Labels: ✨ Feature

#27 [FEAT] BaseTimeEntity 추가
  src/main/java/org/example/baba/common/entity/BaseTimeEntity.java
Labels: ✨ Feature

#38 [ADD] 더미데이터 추가
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: 📃 Docs

#43 [FEAT] 스프링 시큐리티와 JWT 토큰을 이용한 인증
  build.gradle
  src/main/java/org/example/baba/common/config/SecurityConfig.java
  src/main/java/org/example/baba/common/config/dsl/JwtFilterDsl.java
  src/main/java/org/example/baba/common/property/YamlPropertySourceFactory.java
  src/main/java/org/example/baba/common/security/details/AuthUser.java
  src/main/java/org/example/baba/common/security/details/MemberDetailService.java
  src/main/java/org/example/baba/common/security/dto/LoginDto.java
  src/main/java/org/example/baba/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/org/example/baba/common/utils/cookie/CookieProperties.java
  src/main/java/org/example/baba/common/utils/cookie/CookieUtils.java
  src/main/java/org/example/baba/common/utils/jwt/JwtProperties.java
  src/main/java/org/example/baba/common/utils/jwt/JwtProvider.java
  src/main/java/org/example/baba/common/utils/translator/ObjectMapperUtils.java
  src/main/java/org/example/baba/exception/exceptionType/AuthorizedExceptionType.java
  src/main/java/org/example/baba/exception/exceptionType/CommonExceptionType.java
  src/main/java/org/example/baba/repository/MemberRepository.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: ✨ Feature

#45 [TEST] 비밀번호 검증 어노테이션 테스트 완료
  src/main/java/org/example/baba/common/anotation/PasswordValidator.java
  src/main/java/org/example/baba/controller/dto/request/RegisterDTO.java
  src/main/java/org/example/baba/controller/dto/request/dummy.txt
  src/test/java/org/example/baba/common/ValidAnotaionTest.java
Labels: ✅ Test

#46 [FEAT] 게시글 상세보기 API 구현
  src/main/java/org/example/baba/BabaApplication.java
  src/main/java/org/example/baba/controller/PostController.java
  src/main/java/org/example/baba/controller/dto/response/PostDetailResponseDto.java
  src/main/java/org/example/baba/domain/Post.java
  src/main/java/org/example/baba/service/PostService.java
  src/main/resources/data.sql
Labels: ✨ Feature

#48 [FEAT] 게시글 좋아요, 공유 메소드에 외부 API 호출 기능 추가
  build.gradle
  src/main/java/org/example/baba/common/config/WebClientConfig.java
  src/main/java/org/example/baba/exception/exceptionType/PostExceptionType.java
  src/main/java/org/example/baba/service/PostService.java
Labels: 🐞 BugFix, ✨ Feature, 🪄Fix

#50 [FEAT] 가입승인 API 구현
  src/main/java/org/example/baba/common/config/RedisConfig.java
  src/main/java/org/example/baba/controller/MemberController.java
  src/main/java/org/example/baba/controller/dto/request/RegisterDTO.java
  src/main/java/org/example/baba/exception/exceptionType/RegisterExceptionType.java
  src/main/java/org/example/baba/repository/MemberRepository.java
  src/main/java/org/example/baba/service/MemberService.java
  src/main/resources/application.yml
  src/test/java/org/example/baba/common/RedisTest.java
  src/test/java/org/example/baba/common/ValidAnotaionTest.java
  src/test/java/org/example/baba/service/RegisterServiceTest.java
Labels: 🔨 Refactor, ✅ Test, ✨ Feature, 🪄Fix

#52 [FEAT] 스프링 시큐리티 + JWT 토큰 인가 및 예외처리
  src/main/java/org/example/baba/common/config/SecurityConfig.java
  src/main/java/org/example/baba/common/config/dsl/JwtFilterDsl.java
  src/main/java/org/example/baba/common/redis/RedisRepository.java
  src/main/java/org/example/baba/common/security/controller/AuthController.java
  src/main/java/org/example/baba/common/security/dto/MemberInfo.java
  src/main/java/org/example/baba/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/org/example/baba/common/security/filter/JwtVerificationFilter.java
  src/main/java/org/example/baba/common/security/handler/AuthenticationEntryPointHandler.java
  src/main/java/org/example/baba/common/security/handler/AuthenticationFailureCustomHandler.java
  src/main/java/org/example/baba/common/security/handler/LogoutSuccessCustomHandler.java
  src/main/java/org/example/baba/common/security/service/AuthService.java
  src/main/java/org/example/baba/common/utils/cookie/CookieUtils.java
  src/main/java/org/example/baba/common/utils/jwt/JwtProvider.java
  src/main/java/org/example/baba/exception/exceptionType/UserExceptionType.java
Labels: ✨ Feature

#54 [FEAT] 게시글 상세보기 내 해시태그 추가
  src/main/java/org/example/baba/controller/dto/response/PostDetailResponseDto.java
  src/main/java/org/example/baba/controller/dto/response/dummy.txt
  src/main/java/org/example/baba/domain/Post.java
  src/main/java/org/example/baba/exception/exceptionType/PostExceptionType.java
  src/main/java/org/example/baba/repository/PostRepository.java
  src/main/java/org/example/baba/service/PostService.java
  src/main/resources/data.sql
Labels: ✨ Feature

#55 [FIX] 스프링 시큐리티 오류 수정
  src/main/java/org/example/baba/common/config/SecurityConfig.java
  src/main/java/org/example/baba/common/config/dsl/JwtFilterDsl.java
  src/main/java/org/example/baba/common/security/filter/JwtVerificationFilter.java
  src/main/java/org/example/baba/common/security/handler/VerificationAccessDeniedHandler.java
  src/main/java/org/example/baba/exception/exceptionType/AuthorizedExceptionType.java
Labels: 🐞 BugFix

#57 [FEAT] 게시글 목록 조회 API 구현
  src/main/java/org/example/baba/controller/PostController.java
  src/main/java/org/example/baba/controller/dto/response/PostSimpleResponseDto.java
  src/main/java/org/example/baba/repository/PostRepository.java
  src/main/java/org/example/baba/service/PostService.java
  src/main/resources/data.sql
Labels: 📃 Docs, ✨ Feature

#59 [FEAT] 가입승인 API 구현 및 테스트 완료
  src/main/java/org/example/baba/common/config/RedisConfig.java
  src/main/java/org/example/baba/controller/MemberController.java
  src/main/java/org/example/baba/controller/dto/request/RegisterDTO.java
  src/main/java/org/example/baba/domain/ApprovalCode.java
  src/main/java/org/example/baba/domain/Register.java
  src/main/java/org/example/baba/exception/exceptionType/RegisterExceptionType.java
  src/main/java/org/example/baba/repository/ApprovalCodeRepository.java
  src/main/java/org/example/baba/repository/RegisterRepository.java
  src/main/java/org/example/baba/service/MemberService.java
  src/test/java/org/example/baba/common/RedisTest.java
  src/test/java/org/example/baba/service/RegisterServiceTest.java
Labels: 🔨 Refactor, ✅ Test, ✨ Feature

#61 [REFACTOR] 게시글 상세 테스트코드 수정
  build.gradle
  src/test/java/org/example/baba/service/PostServiceTest.java
Labels: 🔨 Refactor, Chore

#56 [FEAT] 통계 API 구현
  .gitignore
  build.gradle
  src/main/java/org/example/baba/common/config/QueryDSLConfig.java
  src/main/java/org/example/baba/common/enums/StatisticsType.java
  src/main/java/org/example/baba/common/enums/StatisticsValue.java
  src/main/java/org/example/baba/controller/StatisticsController.java
  src/main/java/org/example/baba/exception/exceptionType/StatisticsExceptionType.java
  src/main/java/org/example/baba/repository/StatisticsRepository.java
  src/main/java/org/example/baba/service/StatisticsService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: ✨ Feature

#68 [DOCS] README.md 작성
  .gitignore
  README.md
Labels: 📃 Docs

#70 [FEAT] default hashtag 구현
  src/main/java/org/example/baba/common/config/SecurityConfig.java
  src/main/java/org/example/baba/controller/StatisticsController.java
  src/main/java/org/example/baba/exception/exceptionType/StatisticsExceptionType.java
  src/main/java/org/example/baba/service/StatisticsService.java
Labels: ✨ Feature

#69 [TEST] 스프링 시큐리티 테스트
  build.gradle
  src/main/java/org/example/baba/common/config/SecurityConfig.java
  src/main/java/org/example/baba/common/security/service/AuthService.java
  src/main/resources/application.yml
  src/test/java/org/example/baba/common/annotation/WithMockCustomUserSecurityContextFactory.java
  src/test/java/org/example/baba/common/annotation/WithUser.java
  src/test/java/org/example/baba/common/redis/RedisRepositoryTest.java
  src/test/java/org/example/baba/common/security/config/SecurityTestConfig.java
  src/test/java/org/example/baba/common/security/controller/AuthControllerTest.java
  src/test/java/org/example/baba/common/utils/jwt/JwtPropertiesTest.java
  src/test/java/org/example/baba/common/utils/jwt/JwtProviderTest.java
Labels: ✅ Test

#71 [TEST] 게시글 좋아요 기능 테스트코드 작성 및 통과
  src/main/java/org/example/baba/domain/Post.java
  src/main/java/org/example/baba/service/PostService.java
  src/test/java/org/example/baba/service/PostServiceTest.java
Labels: ✅ Test

#72 [TEST] 게시글 공유 기능 테스트코드 작성 및 통과
  src/test/java/org/example/baba/service/PostServiceTest.java
Labels: ✅ Test

#75 [REFACTOR] 게시글 상세보기 테스트코드 수정
  src/test/java/org/example/baba/service/PostServiceTest.java
Labels: 🔨 Refactor

#77 [FEAT] CommonExceptionHandler에서 queryParam 여부/타입에 대한 에러 메시지 분리
  src/main/java/org/example/baba/exception/CustomExceptionHandler.java
  src/main/java/org/example/baba/exception/exceptionType/CommonExceptionType.java
Labels: ✨ Feature

#80 [FIX] 에러 응답 처리 수정
  src/main/java/org/example/baba/common/config/SecurityConfig.java
  src/main/java/org/example/baba/common/security/handler/AuthenticationEntryPointHandler.java
  src/main/java/org/example/baba/common/security/handler/AuthenticationFailureCustomHandler.java
  src/main/java/org/example/baba/common/security/handler/VerificationAccessDeniedHandler.java
Labels: 🪄Fix

#82 [DEL] ObjectMapperUtils 의존성 제거
  src/main/java/org/example/baba/common/security/handler/AuthenticationFailureCustomHandler.java
Labels: Del

#83 [FEAT] 가입승인 메일 전송 기능 구현
  build.gradle
  src/main/java/org/example/baba/service/MemberService.java
  src/main/resources/application.yml
Labels: ✨ Feature, Chore

#86 [DEL] SecurityTestConfig 수정
  src/test/java/org/example/baba/common/security/config/SecurityTestConfig.java
Labels: Del

#87 [REFACTOR] MemberService 기능 분리 및 테스트 완료
  src/main/java/org/example/baba/controller/MemberController.java
  src/main/java/org/example/baba/service/MailService.java
  src/main/java/org/example/baba/service/MemberService.java
  src/main/java/org/example/baba/service/SafeStoreService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/org/example/baba/common/RedisTest.java
  src/test/java/org/example/baba/common/annotation/ValidAnotaionTest.java
  src/test/java/org/example/baba/common/redis/RedisTest.java
  src/test/java/org/example/baba/service/SafeStoreServiceTest.java
Labels: 🔨 Refactor, ✅ Test
